# frozen_string_literal: true

source "https://rubygems.org"

def gembox_source
  "http://#{ENV.fetch('GEMBOX_USERNAME')}:#{ENV.fetch('GEMBOX_PASSWORD')}@localhost:9292"
end

gem "puma"
gem "my_gem", source: gembox_source
